[맵과셋] 3월 8일
Altu-Bitu-2/Altu-Bitu-2-ass-j pull request #2
Opened 2022-03-13 17:01 UTC by 0214jj

#### 내용 & 질문
> 과제 제출합니다!

#### <기존 제출>
> 필수
> 선택: 11478, 19583, 20291, 9375,20920
#### <추가 제출>
>

2022-03-14 02:55 UTC, hoit1302 requested changes
20291번과 20290번은 BOJ `jeeyoun0214` 계정으로의 제출 기록이 직접 돌려서 AC 확인해보았습니다! 그래서 현재, 선택 6문제 중 4문제 제출 확인 되셨습니다. 
추가 제출이 아닌 기존 제출은 백준에서 맞았습니다 를 받아야 제출 인정이 된답니다 ☺️
혹시 왜 제출 기록이 없는지에 대해서 여쭤보아도 될까요 ? 🤗

P1으로 보낸 요청사항이 하나 있습니다! 알고리즘 헤더를 추가해주신 뒤 오른쪽 위 reviewers의 되돌이 아이콘을 클릭해 재리뷰를 요청해주세요 :) 
너무너무 수고하셨습니다. 
좋은 하루 보내세요💛

2022-03-14 02:55 UTC, hoit1302 commented on [map&set]3_8/19583.cpp
> +}
p3. 사소한 의견
이 문제는 꼭 분으로 계산해서 대소비교를 하지 않아도 된답니다.
입력받은 문자열 그대로 대소비교를 할 수 있기 때문이에요!
`"22:00" < "22:05"` -> `true` 를 반환합니다 ☺️

2022-03-14 02:55 UTC, hoit1302 commented on [map&set]3_8/19583.cpp
> +        cin >> time >> name;
p3. 사소한 의견
이렇게 더 간단히 구현할 수 있습니다 !
``` c++
while (cin >> time >> name) {//입력이 없으면 종료
```

2022-03-14 02:55 UTC, hoit1302 commented on [map&set]3_8/20920.cpp
> +    sort(mem.begin(), mem.end(), cmp);
p1. 꼭 반영해주세요
``` c++
#include <algorithm>
```
백준 환경에서 AC를 받기 위해서는 헤더를 추가해주셔야 합니다!

2022-03-14 02:58 UTC, flowersayo reviewed
선택 3문제 제출 확인되셨습니다~! 전반적으로 코드가 너무 깔끔하고 완벽하신데다가 중간중간 필요한 부분에 주석까지 달아주셔서 리뷰하기가 너무 좋았습니다! 
p1 코멘트는 꼭 수정해주셨으면 하는 부분이고 p2, p3는 읽어보시고 참고하시는 정도로만 받아
들이셔도 좋아요! 물론 p2, p3까지 리팩토링 해주시면 더더욱 좋구요!
코드 수정하신 후에 저 리뷰어로 호출해주세요~!!

2022-03-14 02:58 UTC, flowersayo commented on [map&set]3_8/11478.cpp
> +    cout<<s.size()<<'\n';
i  : 문자열의 시작지점
j : 문자열의 길이

로 이중 반복문을 돌리고 substr 함수를 이용해서 모든 부분문자열 경우의 수를 count해주셨네요!
중복이 불가능하다는 set의 특성을 잘 활용해서 `set.size()`가 결국 겹치지 않는 부분 문자열의 전체 수라는 점도 잘 캐치해주셨어요! 저희가 준비한 샘플코드와 거의 일치해서 피드백 드릴게 없네요 ...핳 최고에요🥰🥰

2022-03-14 02:58 UTC, flowersayo commented on [map&set]3_8/19583.cpp
> +
p1.
오오 지금 stoi 랑 substr을 활용해서 시간 단위를 통일해주셨어요! stoi는 숫자 앞에 0이 붙더라도 int형으로 바꿔주는 ( '01' -> 1) 친절한 기능까지 포함하고 있으니 아마 이보다 더 적합한 함수가 없었을거에요! 그런데 사실 string도 대소비교가 가능하다는 점을 활용하면 굳이 string 을 숫자로 맵핑하지 않아도 괜찮아요! 아래 계산식들이 어떤 값을 반환할지 확인해볼까요?

```
'11:00' < '12:35' 
'09:07' > '11:59' 
```

2022-03-14 02:58 UTC, flowersayo commented on [map&set]3_8/19583.cpp
> +    while (!cin.eof()) {//입력이 없으면 종료
👍👍

2022-03-14 02:58 UTC, flowersayo commented on [map&set]3_8/19583.cpp
> +                att.insert(name);
👍👍👍

2022-03-14 02:58 UTC, flowersayo commented on [map&set]3_8/19583.cpp
> +    cout << att.size() << '\n';
set에는 중복된 값이 들어갈 수 없다는 점을 참고해서 `set.size()` 에는 어떤값이 담기게 되는지 정확히 캐치해주셨네요! 👍👍👍

2022-03-14 02:58 UTC, flowersayo commented on [map&set]3_8/20291.cpp
> +        file.erase(0,file.find('.')+1);
p2.
우오! 지금 `.` 이 등장하는 인덱스 앞부분들을 모두 날려서 확장자를 더하고 있어요! 
`abcd.txt` -> `txt` 
이렇게 처리하는 방법은 처음봤는데 이 방법도 굉장히 깔끔하고 좋네요! 

+ 그런데 사실 erase는 조금 위험한 함수에요! 물론 지금은 해당되지 않지만..  만약 파일의 이름 정보를 계속적으로 유지해야하는 상황이었다면 erase함수보다는 `substr` 을 활용해서 **확장자를 추출** 하는 방식으로 작성해봤어도 좋을 것 같아요! 물론 지금도 너무너무 잘 작성해주셨어요🥰

2022-03-14 02:58 UTC, flowersayo commented on [map&set]3_8/20920.cpp
> +        w[word]++;
p1.
단어장에 있는지, 없는지 확인하는 부분은 작성해주지 않으셔도 괜찮아요!  한번 map에서 없는 key값에 접근할때 어떤 value를 가지게 되는지 확인해볼까요? map&set PPT 의 이것도 알아보세요 부분을 참고해보세요!

2022-03-14 02:58 UTC, flowersayo commented on [map&set]3_8/9375.cpp
> +    }
옷의 종류와 가짓수를 map 컨테이너에 잘 저장시켜서 모든 경우의 수를 곱하고, 알몸인 경우를 빼야하는 함정까지 잘 피해가셨어요! 👍 코드가 너무 완벽해서 제가 더이상 드릴 피드백이 없네요 헣,,

2022-03-15 02:33 UTC, flowersayo commented on [map&set]3_8/20920.cpp
> +            w[word]=0;
핳 제가 커멘트를 조금 애매하게 드렸나보네요! 없는 단어일경우는 어짜피 w[word] =0 인 상태이니 37번째줄은 제거해도 상관없다는 의미였어요~!!

2022-03-15 02:35 UTC, flowersayo commented
선택 5문제 모두 제출 확인되셨습니다 메인에 머지하셔도 좋아요~!! 수고하셨습니다 🥰

2022-03-15 07:37 UTC, merged